### ISSUE TITLE
ASk for pca_byol.vt

### ISSUE THREAD

**Issue by renrenzsbbb** [WangWenhao0716/ISC-Track1-Submission#2]
Thanks for you great work. Can you offer your pca_byol.vt file. Thanks in advance.

**Comment by WangWenhao0716** [comment]
Sorry, all the extracted features (include pca_byol.vt) are deleted. However, it only takes a minute to get one pca_byol.vt using one of my uploaded trained models and training images. Hope that helps!

**Comment by renrenzsbbb** [comment]
Thanks for your response. But it is hard for me to download all image.Can I use the test image to get pca_byol.vt or other alternative method? Thanks.

**Comment by renrenzsbbb** [comment]
If I directly use the feature from pretrained model, can I get the similar results?

**Comment by WangWenhao0716** [comment]
You should download all the training images. The images are also used when performing score normalization. They are a must. By the way, AWS is accessible.

**Comment by renrenzsbbb** [comment]
Get it. Thanks for your response.
