### ISSUE TITLE
求yolo训练代码

### ISSUE THREAD

**Issue by mr-lz** [WangWenhao0716/ISC-Track1-Submission#4]
halo老兄，yolov5的训练代码能否放出来学习一下呢(⁄⁄•⁄ω⁄•⁄⁄)⁄

**Comment by WangWenhao0716** [comment]
For the training code, please write a request email (with your purpose and your personal information) to wangwenhao0716@gmail.com.

**Comment by mr-lz** [comment]
> For the training code, please write a request email (with your purpose and your personal information) to [wangwenhao0716@gmail.com](mailto:wangwenhao0716@gmail.com).

OK, thanks for your reply.
